[workspace]
members = [
    "rusty_template",
    "macros",

    # ---
    "examples",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
rusty_template = { path = "./rusty_template" }
macros = { path = "./macros" }
thiserror = "1.0"
