[package]
name = "macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.69"
syn = { version = "2.0.38", features = ["full", "extra-traits" ] }
quote = "1.0"
